import { Badge } from '../ui/Badge';
import { EmptyState } from '../ui/EmptyState';
import { Progress } from '../ui/Progress';
import { duration, fmt, label, remaining } from '../../app/format';
import type { Catalog, State } from '../../types/game';

export function ContextPanel({ catalog, state }: { catalog: Catalog; state: State }) {
  const active = state.construction.length + (state.research.active ? 1 : 0) + state.fleets.filter(fleet => fleet.status === 'TRANSIT').length + state.ships.filter(ship => ship.ready_at > Date.now() / 1000).length;
  return <aside className="context-panel" aria-label="Contexto operacional"><div className="context-heading"><span>OPERAÇÕES</span><b>{active}</b></div>{state.construction.map(job => <div className="queue-item" key={`construction-${job.id}`}><div><b>{label(catalog, job.id)}</b><Badge tone="blue">CONSTRUÇÃO</Badge></div><Progress value={100 * (Date.now() / 1000 - job.started_at) / (job.complete_at - job.started_at)} text={`${remaining(job.complete_at)} restantes`} /></div>)}{state.research.active && <div className="queue-item"><div><b>{label(catalog, state.research.active)}</b><Badge tone="blue">PESQUISA</Badge></div><Progress value={100 * (1 - state.research.remaining_work / Math.max(1, catalog.technologies.find(item => item.id === state.research.active)?.duration ?? 1))} text={remaining(state.research.complete_at)} /></div>}{state.fleets.filter(fleet => fleet.status === 'TRANSIT').map(fleet => <div className="queue-item" key={fleet.id}><div><b>{fleet.name}</b><Badge tone="blue">EM TRÂNSITO</Badge></div><Progress value={100 * (Date.now() / 1000 - fleet.departure_at) / Math.max(1, fleet.arrival_at - fleet.departure_at)} text={`${duration(fleet.eta)} · ${fleet.destination_x}:${fleet.destination_y}`} /></div>)}{active === 0 && <EmptyState title="Operações estáveis">Nenhuma atividade temporal em andamento.</EmptyState>}<div className="context-heading context-alerts"><span>REGISTRO RECENTE</span></div><div className="notice-list">{state.notices.length ? state.notices.map(message => <div className="notice" key={message}><i /><span>{message}</span></div>) : <span className="muted">Sem novos registros.</span>}</div></aside>;
}
