import { Icon } from '../ui/Icon';
import { fmt, nominalRate, strategicResources } from '../../app/format';
import type { Catalog, PlanetTab, State } from '../../types/game';

export function PlanetInspector({ catalog, state, tab, onTab }: { catalog: Catalog; state: State; tab: PlanetTab; onTab: (tab: PlanetTab) => void }) {
  const p = state.system.planet;
  const tabs: Array<[PlanetTab, string]> = [['overview', 'Visão geral'], ['districts', 'Distritos'], ['orbit', 'Órbita'], ['data', 'Dados']];
  const physical = [['Gravidade', `${fmt(p.gravity, 2)} g`], ['Temperatura', `${fmt(p.temperature)} K`], ['Água', `${fmt(p.water, 1)}%`], ['Atmosfera', p.atmosphere], ['Radiação', fmt(p.radiation, 2)], ['Campo magnético', fmt(p.magnetic_field, 2)], ['Superfície útil', `${fmt(p.usable_surface, 1)}%`], ['Atividade geológica', fmt(p.geological_activity, 2)]];
  const development = [['População', `${fmt(state.population.total)} / ${fmt(state.population.capacity)}`], ['Workforce', `${fmt(state.capacities.workforce_supply)} / ${fmt(state.capacities.workforce_demand)}`], ['Energia', `${fmt(state.capacities.energy_generation)} / ${fmt(state.capacities.energy_consumption)}`], ['Capacidade industrial', fmt(state.capacities.industrial_capacity)], ['Slots de construção', `${fmt(state.capacities.construction_slots - state.capacities.construction_slots_available)} / ${fmt(state.capacities.construction_slots)}`], ['Slots de estaleiro', `${fmt(state.capacities.shipyard_slots - state.capacities.shipyard_slots_available)} / ${fmt(state.capacities.shipyard_slots)}`]];
  const body = tab === 'districts' ? <div className="entity-list">{catalog.districts.map(district => <div className="entity-row" key={district.id}><div><b>{district.name}</b><small>{district.description}</small></div><strong>{state.districts[district.id] ?? 0}</strong></div>)}</div> : tab === 'orbit' ? <div className="facts-grid">{state.fleets.filter(fleet => fleet.x === state.system.x && fleet.y === state.system.y).map(fleet => <div className="stat" key={fleet.id}><span>{fleet.name}</span><strong>{fleet.status}</strong></div>)}{state.capacities.shipyard_slots > 0 && <div className="stat"><span>Estaleiro orbital</span><strong>Ativo</strong></div>}</div> : tab === 'data' ? <pre className="data-preview">{JSON.stringify({ coordinates: [state.system.x, state.system.y], planet_index: state.active_planet?.planet_index, star: state.system.star }, null, 2)}</pre> : <><div className="summary-strip"><div className="planet-summary-art" /><div><span className="eyebrow">PLANETARY PROFILE</span><strong>{state.system.planet.name}</strong><small>{state.system.name}</small></div></div><div className="inspector-section"><div className="section-heading"><span>CARACTERÍSTICAS FÍSICAS</span><Icon name="planet" className="ui-icon orbit-glyph" /></div><div className="spec-grid">{physical.map(([name, value]) => <div className="spec" key={name}><span>{name}</span><strong>{value}</strong></div>)}</div></div><div className="inspector-section"><div className="section-heading"><span>DESENVOLVIMENTO</span><Icon name="operations" className="ui-icon orbit-glyph" /></div><div className="development-list">{development.map(([name, value]) => <div className="development-row" key={name}><span>{name}</span><strong>{value}</strong></div>)}</div></div><div className="inspector-section"><div className="section-heading"><span>PRODUÇÃO DE RECURSOS</span></div><div className="production-list">{strategicResources(catalog, state).map(item => <div className="prod-row" key={item.id}><span>{item.name}</span><strong>{nominalRate(catalog, state, item.id) > 0 ? `+${fmt(nominalRate(catalog, state, item.id) * 60, 1)}/h` : '—'}</strong></div>)}</div><small className="muted">Produção nominal · antes de limitações operacionais.</small></div></>;
  return <aside className="planet-inspector" aria-label="Informações do planeta"><div className="inspector-tabs" role="tablist">{tabs.map(([id, name]) => <button key={id} role="tab" aria-selected={tab === id} className={tab === id ? 'selected' : ''} onClick={() => onTab(id)}>{name}</button>)}</div><div className="inspector-body">{body}</div></aside>;
}
