import { Icon } from '../ui/Icon';
import { DataRow } from '../ui/DataRow';
import { Inspector, InspectorSection } from '../ui/Inspector';
import { Tabs } from '../ui/Tabs';
import { fmt, nominalRate, strategicResources } from '../../app/format';
import type { Catalog, PlanetTab, State } from '../../types/game';

export function PlanetInspector({ catalog, state, tab, onTab }: { catalog: Catalog; state: State; tab: PlanetTab; onTab: (tab: PlanetTab) => void }) {
  const p = state.system.planet;
  const tabs: Array<[PlanetTab, string]> = [['overview', 'Visão geral'], ['districts', 'Distritos'], ['orbit', 'Órbita'], ['data', 'Dados']];
  const physical = [['Gravidade', `${fmt(p.gravity, 2)} g`], ['Temperatura', `${fmt(p.temperature)} K`], ['Água', `${fmt(p.water, 1)}%`], ['Atmosfera', p.atmosphere], ['Radiação', fmt(p.radiation, 2)], ['Campo magnético', fmt(p.magnetic_field, 2)], ['Superfície útil', `${fmt(p.usable_surface, 1)}%`], ['Atividade geológica', fmt(p.geological_activity, 2)]];
  const development = [['População', `${fmt(state.population.total)} / ${fmt(state.population.capacity)}`], ['Workforce', `${fmt(state.capacities.workforce_supply)} / ${fmt(state.capacities.workforce_demand)}`], ['Energia', `${fmt(state.capacities.energy_generation)} / ${fmt(state.capacities.energy_consumption)}`], ['Capacidade industrial', fmt(state.capacities.industrial_capacity)], ['Slots de construção', `${fmt(state.capacities.construction_slots - state.capacities.construction_slots_available)} / ${fmt(state.capacities.construction_slots)}`], ['Slots de estaleiro', `${fmt(state.capacities.shipyard_slots - state.capacities.shipyard_slots_available)} / ${fmt(state.capacities.shipyard_slots)}`]];
  const body = tab === 'districts' ? <div className="entity-list">{catalog.districts.map(district => <div className="entity-row" key={district.id}><div><b>{district.name}</b><small>{district.description}</small></div><strong>{state.districts[district.id] ?? 0}</strong></div>)}</div> : tab === 'orbit' ? <div className="facts-grid">{state.fleets.filter(fleet => fleet.x === state.system.x && fleet.y === state.system.y).map(fleet => <div className="stat" key={fleet.id}><span>{fleet.name}</span><strong>{fleet.status}</strong></div>)}{state.capacities.shipyard_slots > 0 && <div className="stat"><span>Estaleiro orbital</span><strong>Ativo</strong></div>}</div> : tab === 'data' ? <pre className="data-preview">{JSON.stringify({ coordinates: [state.system.x, state.system.y], planet_index: state.active_planet?.planet_index, star: state.system.star }, null, 2)}</pre> : <><div className="summary-strip"><div className="planet-summary-art" /><div><span className="eyebrow">PLANETARY PROFILE</span><strong>{state.system.planet.name}</strong><small>{state.system.name}</small></div></div><InspectorSection title="Características físicas" action={<Icon name="planet" className="ui-icon orbit-glyph" />}><div className="spec-grid">{physical.map(([name, value]) => <DataRow label={name} value={value} key={name} />)}</div></InspectorSection><InspectorSection title="Desenvolvimento" action={<Icon name="operations" className="ui-icon orbit-glyph" />}><div className="development-list">{development.map(([name, value]) => <DataRow label={name} value={value} key={name} />)}</div></InspectorSection><InspectorSection title="Produção de recursos"><div className="production-list">{strategicResources(catalog, state).map(item => <DataRow label={item.name} value={nominalRate(catalog, state, item.id) > 0 ? `+${fmt(nominalRate(catalog, state, item.id) * 60, 1)}/h nom.` : '—'} tone="positive" key={item.id} />)}</div><small className="muted">Produção nominal · antes de limitações operacionais.</small></InspectorSection></>;
  return <Inspector label="Informações do planeta" className="planet-inspector" header={<Tabs items={tabs.map(([id, name]) => ({ id, label: name }))} value={tab} onChange={onTab} label="Seções do planeta" />}>{body}</Inspector>;
}
