import { useOutletContext } from 'react-router-dom';
import { Panel } from '../components/ui/Panel';
import { fmt, nominalRate, strategicResources } from '../app/format';
import type { ShellContext } from '../components/shell/AppShell';

export function EconomyView() {
  const { catalog, state } = useOutletContext<ShellContext>();
  return <><header className="page-header"><div><div className="eyebrow">PLANETARY ECONOMY</div><h1>Economia</h1><p>Estoque físico de {state.system.planet.name}. Recursos não são compartilhados entre mundos.</p></div></header><div className="three-columns"><Panel title="Stocks locais" eyebrow="STOCK"><div className="resource-list">{strategicResources(catalog, state).map(item => <div key={item.id}><span>{item.name}</span><b>{fmt(state.stocks[item.id], 1)}</b></div>)}</div></Panel><Panel title="Produção nominal" eyebrow="FLOW"><div className="resource-list">{strategicResources(catalog, state).map(item => <div key={item.id}><span>{item.name}</span><b>{nominalRate(catalog, state, item.id) > 0 ? `+${fmt(nominalRate(catalog, state, item.id), 2)}/min` : '—'}</b></div>)}</div></Panel><Panel title="Capacidades" eyebrow="CAPACITY"><div className="metric-line"><span>Energia</span><b>{fmt(state.capacities.energy_generation)} / {fmt(state.capacities.energy_consumption)}</b></div><div className="metric-line"><span>Workforce</span><b>{fmt(state.capacities.workforce_supply)} / {fmt(state.capacities.workforce_demand)}</b></div><div className="metric-line"><span>Indústria</span><b>{fmt(state.capacities.industrial_capacity)}</b></div></Panel></div><Panel title="Processamento local" eyebrow="PLANET"><div className="entity-list">{catalog.districts.filter(item => Object.keys(item.processing).length || Object.keys(item.production).length).map(item => <div className="entity-row" key={item.id}><div><b>{item.name}</b><small>{item.description}</small></div><strong>nível {state.districts[item.id] ?? 0}</strong><span>{Object.entries(item.processing).map(([id, value]) => `${fmt(value, 2)} ${id}`).join(', ') || 'produção direta'}</span></div>)}</div></Panel></>;
}
